"""
Reference report template for Bennu analyses.

Provides a standardized, parameterizable report generator that can be
customized for different organism types while maintaining consistent formatting.
"""

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from fpdf import FPDF


def clean_text(text: str) -> str:
    """Clean text for PDF rendering - handle unicode."""
    if not text:
        return ""
    replacements = {
        '\u2192': '->', '\u2190': '<-', '\u2194': '<->',
        '\u2265': '>=', '\u2264': '<=', '\u2260': '!=',
        '\u03b1': 'alpha', '\u03b2': 'beta', '\u03b3': 'gamma',
        '\u03b4': 'delta', '\u03b5': 'epsilon', '\u03bc': 'mu',
        '\u2022': '*', '\u2013': '-', '\u2014': '--',
        '\u201c': '"', '\u201d': '"', '\u2018': "'", '\u2019': "'",
        '\u00b0': ' deg', '\u00b5': 'u', '\u00d7': 'x',
        '\u2248': '~', '\u221e': 'inf', '\u00b1': '+/-',
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text.encode('latin-1', 'replace').decode('latin-1')


class BennuReport(FPDF):
    """
    Base report class with consistent styling.

    Color themes:
        - default: Blue-gray (#607D8B)
        - archaeal: Green (#2E7D32)
        - viral: Purple (#6A1B9A)
        - bacterial: Teal (#00838F)
    """

    THEMES = {
        "default": {"primary": (96, 125, 139), "secondary": (120, 144, 156)},
        "archaeal": {"primary": (46, 125, 50), "secondary": (67, 160, 71)},
        "viral": {"primary": (106, 27, 154), "secondary": (142, 68, 173)},
        "bacterial": {"primary": (0, 131, 143), "secondary": (38, 166, 154)},
    }

    def __init__(self, theme: str = "default", title: str = "Bennu Analysis Report"):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(left=20, top=15, right=20)
        self.toc_entries = []
        self.in_toc = False
        self.figure_counter = 0
        self.theme = self.THEMES.get(theme, self.THEMES["default"])
        self.report_title = title

    def _rgb(self, key: str = "primary"):
        return self.theme[key]

    def header(self):
        if self.page_no() > 1:
            self.set_draw_color(*self._rgb())
            self.set_line_width(0.3)
            self.line(20, 12, self.w - 20, 12)
            self.set_font('Helvetica', 'I', 8)
            self.set_text_color(100, 100, 100)
            self.cell(0, 8, self.report_title[:60], 0, 0, 'L')
            self.cell(0, 8, f'Page {self.page_no()}', 0, 0, 'R')
            self.ln(12)
            self.set_text_color(0, 0, 0)

    def footer(self):
        if self.in_toc:
            return
        self.set_y(-15)
        self.set_draw_color(*self._rgb())
        self.set_line_width(0.2)
        self.line(20, self.h - 18, self.w - 20, self.h - 18)
        self.set_font('Helvetica', 'I', 7)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, 'Generated by Bennu Metagenomic Analysis System', 0, 0, 'C')

    def chapter_title(self, num: int, title: str, add_to_toc: bool = True):
        if add_to_toc:
            self.toc_entries.append((num, title, self.page_no()))
        self.set_font('Helvetica', 'B', 16)
        self.set_fill_color(*self._rgb())
        self.set_text_color(255, 255, 255)
        self.set_x(self.l_margin + 1)
        self.cell(self.w - self.l_margin - self.r_margin - 1, 12,
                  f'  {num}. {clean_text(title)}', 0, 1, 'L', True)
        self.set_text_color(0, 0, 0)
        self.ln(6)

    def section_title(self, title: str):
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(*self._rgb())
        self.multi_cell(self.w - self.l_margin - self.r_margin, 8,
                        clean_text(title)[:100], align='L')
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def subsection_title(self, title: str):
        self.set_font('Helvetica', 'B', 10)
        r, g, b = self._rgb("secondary")
        self.set_text_color(r, g, b)
        self.multi_cell(self.w - self.l_margin - self.r_margin, 7,
                        clean_text(title)[:120], align='L')
        self.set_text_color(0, 0, 0)
        self.ln(1)

    def body_text(self, text: str):
        if not text:
            return
        self.set_font('Helvetica', '', 10)
        self.multi_cell(self.w - self.l_margin - self.r_margin, 5,
                        clean_text(text), align='L')
        self.ln(2)

    def add_bullet(self, text: str):
        self.set_font('Helvetica', '', 10)
        self.set_x(self.l_margin + 5)
        self.cell(5, 5, chr(149), 0, 0)
        self.multi_cell(self.w - self.get_x() - self.r_margin, 5,
                        clean_text(text), align='L')

    def add_evidence_box(self, text: str):
        self.set_font('Helvetica', 'I', 9)
        r, g, b = self._rgb()
        self.set_fill_color(r + 140, g + 100, b + 80)  # Lighter version
        self.set_text_color(r, g, b)
        self.set_x(self.l_margin)
        self.multi_cell(self.w - self.l_margin - self.r_margin, 5,
                        f"  {clean_text(text)}", 0, 'L', True)
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def add_table(self, headers: list, data: list, col_widths: Optional[list] = None):
        if not data:
            return
        n_cols = len(headers)
        available = self.w - self.l_margin - self.r_margin - 4
        if col_widths is None:
            col_widths = [available / n_cols] * n_cols

        self.maybe_add_page(40)

        # Header row
        self.set_font('Helvetica', 'B', 9)
        self.set_fill_color(*self._rgb())
        self.set_text_color(255, 255, 255)
        self.set_x(self.l_margin + 2)
        for i, h in enumerate(headers):
            self.cell(col_widths[i], 6, clean_text(str(h))[:25], 1, 0, 'C', True)
        self.ln()

        # Data rows
        self.set_font('Helvetica', '', 8)
        self.set_text_color(40, 40, 40)
        r, g, b = self._rgb()
        for row_idx, row in enumerate(data):
            if row_idx % 2 == 0:
                self.set_fill_color(r + 160, g + 130, b + 110)
            else:
                self.set_fill_color(255, 255, 255)
            self.set_x(self.l_margin + 2)
            for i, cell in enumerate(row):
                self.cell(col_widths[i], 5, clean_text(str(cell))[:35], 1, 0, 'L', True)
            self.ln()
        self.set_text_color(0, 0, 0)
        self.ln(3)

    def add_image_with_legend(self, path: str, title: str, caption: str,
                               width: int = 170) -> bool:
        """
        Add image with proper figure legend.

        Args:
            path: Path to image file
            title: Short descriptive title (e.g., "CRISPR-Cas Locus")
            caption: 2-4 sentence explanation of what's shown
            width: Image width in mm

        Returns:
            True if image was added, False if file not found
        """
        if not os.path.exists(path):
            return False
        try:
            self.figure_counter += 1
            self.maybe_add_page(85)
            self.image(path, x=20, w=width)
            self.ln(3)

            # Figure legend with number
            self.set_font('Helvetica', 'B', 9)
            self.set_text_color(*self._rgb())
            fig_title = f"Figure {self.figure_counter}: {title}"
            self.cell(0, 5, clean_text(fig_title), 0, 1, 'L')

            # Caption
            self.set_font('Helvetica', '', 8)
            self.set_text_color(60, 60, 60)
            self.multi_cell(self.w - self.l_margin - self.r_margin, 4,
                           clean_text(caption), align='L')
            self.set_text_color(0, 0, 0)
            self.ln(5)
            return True
        except Exception:
            return False

    def add_separator(self):
        self.ln(2)
        r, g, b = self._rgb("secondary")
        self.set_draw_color(r + 60, g + 60, b + 60)
        self.set_line_width(0.2)
        y = self.get_y()
        self.line(self.l_margin + 20, y, self.w - self.r_margin - 20, y)
        self.ln(4)

    def add_toc_entry(self, num: int, title: str, page: int):
        self.set_font('Helvetica', '', 11)
        self.set_text_color(40, 40, 40)
        text = f"{num}. {title}"
        text_width = self.get_string_width(text)
        page_str = str(page)
        page_width = self.get_string_width(page_str)
        available = self.w - self.l_margin - self.r_margin - text_width - page_width - 5
        dot_width = self.get_string_width(' . ')
        num_dots = int(available / dot_width)
        dots = ' .' * num_dots

        self.cell(text_width + 2, 7, text, 0, 0, 'L')
        self.set_text_color(180, 180, 180)
        self.cell(available, 7, dots, 0, 0, 'L')
        self.set_text_color(*self._rgb())
        self.set_font('Helvetica', 'B', 11)
        self.cell(page_width + 3, 7, page_str, 0, 1, 'R')
        self.set_text_color(0, 0, 0)

    def maybe_add_page(self, min_space: int = 60):
        if self.get_y() > (self.h - self.b_margin - min_space):
            self.add_page()

    def create_title_page(self, title: str, subtitle: str, stats: dict):
        """
        Create a formatted title page.

        Args:
            title: Main title
            subtitle: Subtitle (e.g., organism type)
            stats: Dict with key statistics to display
        """
        self.add_page()

        # Top bars
        self.set_fill_color(*self._rgb())
        self.rect(0, 0, self.w, 8, 'F')
        r, g, b = self._rgb("secondary")
        self.set_fill_color(r, g, b)
        self.rect(0, 8, self.w, 3, 'F')

        self.ln(50)
        self.set_font('Helvetica', 'B', 28)
        self.set_text_color(*self._rgb())
        self.cell(0, 15, clean_text(title), 0, 1, 'C')

        self.set_font('Helvetica', '', 18)
        r, g, b = self._rgb("secondary")
        self.set_text_color(r, g, b)
        self.cell(0, 10, clean_text(subtitle), 0, 1, 'C')

        self.ln(5)
        self.set_font('Helvetica', 'I', 14)
        self.cell(0, 10, 'Comprehensive Genome Analysis', 0, 1, 'C')

        # Decorative line
        self.ln(10)
        self.set_draw_color(*self._rgb())
        self.set_line_width(0.8)
        self.line(50, self.get_y(), self.w - 50, self.get_y())
        self.ln(15)

        # Stats
        self.set_text_color(60, 60, 60)
        self.set_font('Helvetica', '', 11)
        stat_lines = []
        for key, value in stats.items():
            stat_lines.append(f"{key}: {value}")
        self.cell(0, 8, "  |  ".join(stat_lines), 0, 1, 'C')

        self.ln(8)
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8, f'Generated: {datetime.now().strftime("%B %d, %Y")}', 0, 1, 'C')

        # Bottom bar
        self.set_fill_color(*self._rgb())
        self.rect(0, self.h - 8, self.w, 8, 'F')

    def create_toc(self) -> int:
        """Create table of contents page. Returns page number."""
        toc_page = self.page_no() + 1
        self.add_page()
        self.in_toc = True
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(*self._rgb())
        self.cell(0, 12, 'Table of Contents', 0, 1, 'L')
        self.set_draw_color(*self._rgb())
        self.set_line_width(0.5)
        self.line(self.l_margin, self.get_y(), self.l_margin + 60, self.get_y())
        self.ln(12)
        self.toc_y_start = self.get_y()
        self.in_toc = False
        return toc_page

    def fill_toc(self, toc_page: int):
        """Fill in TOC after all content is added."""
        total_pages = self.page_no()
        self.page = toc_page
        self.set_y(self.toc_y_start)
        self.in_toc = True
        for num, title, page in self.toc_entries:
            self.add_toc_entry(num, title, page)
        self.in_toc = False
        self.page = total_pages


def generate_report_from_manifest(
    manifest_path: str,
    output_path: Optional[str] = None,
    theme: str = "default",
) -> str:
    """
    Generate a PDF report from an analysis manifest.

    Args:
        manifest_path: Path to manifest.json
        output_path: Output PDF path (default: same dir as manifest)
        theme: Color theme (default, archaeal, viral, bacterial)

    Returns:
        Path to generated PDF
    """
    manifest_path = Path(manifest_path)
    with open(manifest_path) as f:
        manifest = json.load(f)

    data_dir = manifest_path.parent
    dataset_name = manifest.get("dataset", {}).get("name", "Unknown")

    if output_path is None:
        output_path = data_dir / f"{dataset_name}_report.pdf"

    # Auto-detect theme from dataset name
    if theme == "default":
        name_lower = dataset_name.lower()
        if any(x in name_lower for x in ["archae", "thermo", "methano"]):
            theme = "archaeal"
        elif any(x in name_lower for x in ["virus", "phage", "ncldv"]):
            theme = "viral"
        elif any(x in name_lower for x in ["bacter", "pseudo", "strepto"]):
            theme = "bacterial"

    pdf = BennuReport(theme=theme, title=f"{dataset_name} Analysis")

    # Get stats
    annotations = manifest.get("annotations", {})
    total_proteins = sum(v.get("count", 0) for v in annotations.values()
                        if isinstance(v, dict) and "count" in v)
    n_findings = manifest.get("findings", {}).get("count", 0)
    n_structures = manifest.get("structures", {}).get("predicted", 0)

    # Title page
    pdf.create_title_page(
        title=dataset_name.replace("_", " ").title(),
        subtitle="Metagenomic Analysis",
        stats={
            "Annotations": total_proteins,
            "Findings": n_findings,
            "Structures": n_structures,
        }
    )

    # TOC
    toc_page = pdf.create_toc()

    # Executive Summary
    pdf.add_page()
    pdf.chapter_title(1, "Executive Summary")

    exploration = manifest.get("exploration", {})
    status = exploration.get("status", "unknown")
    pdf.body_text(f"Analysis status: {status}")

    # High priority findings
    high_priority = manifest.get("findings", {}).get("high_priority", [])
    if high_priority:
        pdf.section_title("Key Findings")
        for finding in high_priority[:5]:
            pdf.add_bullet(finding.get("title", "Untitled"))

    # Annotations section
    pdf.add_page()
    pdf.chapter_title(2, "Annotation Summary")

    ann_data = []
    for source, info in annotations.items():
        if isinstance(info, dict) and "count" in info:
            ann_data.append([source.upper(), str(info["count"]),
                           f"{info.get('coverage', 0)*100:.1f}%"])
    if ann_data:
        pdf.add_table(["Source", "Count", "Coverage"], ann_data, [50, 50, 50])

    # Structures section
    if n_structures > 0:
        pdf.add_page()
        pdf.chapter_title(3, "Structure Predictions")

        structures = manifest.get("structures", {}).get("proteins", [])
        struct_data = []
        for s in structures[:15]:
            pid = s.get("protein_id", "")[-20:]
            length = s.get("length", "?")
            plddt = f"{s.get('plddt_mean', 0):.2f}" if s.get("plddt_mean") else "N/A"
            interp = s.get("interpretation", "")[:30]
            struct_data.append([pid, str(length), plddt, interp])

        if struct_data:
            pdf.add_table(["Protein", "Length", "pLDDT", "Interpretation"],
                         struct_data, [45, 30, 30, 65])

    # Figures section
    figures = manifest.get("figures", [])
    if figures:
        pdf.add_page()
        pdf.chapter_title(4, "Genomic Neighborhood Diagrams")

        for fig in figures:
            fig_path = data_dir / fig.get("path", "")
            if fig_path.exists():
                pdf.add_image_with_legend(
                    str(fig_path),
                    fig.get("title", "Untitled Figure"),
                    fig.get("legend", "No description provided.")
                )

    # Methods
    pdf.add_page()
    pdf.chapter_title(5 if figures else 4, "Methods")
    pdf.body_text("""
Analysis performed using Bennu metagenomic analysis framework.

- Annotation: PFAM/KEGG via HMM search, VOGdb for viral proteins
- Embeddings: ESM2 (320-dimensional)
- Structure prediction: ESM3 API
- Structural homology: Foldseek against AlphaFold DB and PDB
- Database: DuckDB with LanceDB vector store
    """)

    # Fill TOC
    pdf.fill_toc(toc_page)

    # Save
    pdf.output(str(output_path))
    return str(output_path)


__all__ = [
    "BennuReport",
    "generate_report_from_manifest",
    "clean_text",
]
