"""
CAZy family to predicate mappings.

``data/cazy_predicates.tsv`` is generated by ``scripts/build_cazy_predicate_map.py``:
every (family, predicate) pair in it is supported by CAZy's definition of the
family's class (``class:GH``) or by consensus among reviewed Swiss-Prot proteins
cross-referenced to the family (``swissprot:...``), and records that evidence.
Proposals live in ``data/cazy_predicate_proposals.tsv``; edit those and rebuild.

Families absent from the map (for example families newer than the build) take
their class predicates. Subfamilies (``GH5_2``) resolve to their family.
"""

from __future__ import annotations

import re
from pathlib import Path


# CAZy classes as CAZy defines them. CE includes de-N-acetylases (CE4, CE9,
# CE11), so the class states hydrolase activity, and esterase activity comes
# from family-level evidence.
CAZY_CLASS_PREDICATES: dict[str, list[str]] = {
    "GH": ["carbohydrate_active", "glycoside_hydrolase", "hydrolase"],
    "GT": ["carbohydrate_active", "glycosyltransferase_cazy", "transferase"],
    "PL": ["carbohydrate_active", "polysaccharide_lyase", "lyase"],
    "CE": ["carbohydrate_active", "carbohydrate_esterase", "hydrolase"],
    "CBM": ["carbohydrate_active", "carbohydrate_binding"],
    "AA": ["carbohydrate_active", "auxiliary_activity", "oxidoreductase"],
}

CAZY_MAPPING_FILE = Path(__file__).with_name("data") / "cazy_predicates.tsv"
_FAMILY = re.compile(r"^(GH|GT|PL|CE|CBM|AA)(\d+)")


def cazy_family(name: str) -> str:
    """``GH5_2`` / ``gh5`` / ``GH5.hmm`` -> ``GH5``; unrecognized names are returned stripped."""
    match = _FAMILY.match(name.strip().upper())
    return f"{match.group(1)}{int(match.group(2))}" if match else name.strip()


def cazy_class(family: str) -> str | None:
    """CAZy class (GH, GT, PL, CE, CBM, AA) of a family, or None."""
    match = _FAMILY.match(family.strip().upper())
    return match.group(1) if match else None


def _load_cazy_mapping_file(path: Path) -> tuple[dict[str, list[str]], dict[str, dict[str, str]]]:
    predicates: dict[str, list[str]] = {}
    evidence: dict[str, dict[str, str]] = {}
    with path.open() as handle:
        for line_number, raw_line in enumerate(handle, start=1):
            if not raw_line.strip() or raw_line.startswith("#"):
                continue
            family, preds, ev = raw_line.rstrip("\n").split("\t")
            pred_list = sorted(p for p in preds.split(",") if p)
            ev_map = dict(item.split("=", 1) for item in ev.split(";") if item)
            if set(ev_map) != set(pred_list):
                raise ValueError(f"{path}:{line_number}: evidence does not cover every predicate")
            predicates[family] = pred_list
            evidence[family] = ev_map
    return predicates, evidence


CAZY_TO_PREDICATES, CAZY_EVIDENCE = _load_cazy_mapping_file(CAZY_MAPPING_FILE)


def cazy_evidence(family: str) -> dict[str, str]:
    """Evidence per predicate for a family (class rules for families absent from the map)."""
    family = cazy_family(family)
    if family in CAZY_EVIDENCE:
        return dict(CAZY_EVIDENCE[family])
    klass = cazy_class(family)
    return {p: f"class:{klass}" for p in CAZY_CLASS_PREDICATES.get(klass, ())} if klass else {}


def get_predicates_for_cazy(family: str) -> list[str]:
    """Predicate IDs for a CAZy family (e.g. "GH5", "GH5_2", "AA9", "CBM1")."""
    return sorted(cazy_evidence(family))


def get_cazy_class(family: str) -> str | None:
    """Backward-compatible alias of :func:`cazy_class`."""
    return cazy_class(family)


__all__ = [
    "CAZY_CLASS_PREDICATES",
    "CAZY_EVIDENCE",
    "CAZY_TO_PREDICATES",
    "cazy_class",
    "cazy_evidence",
    "cazy_family",
    "get_cazy_class",
    "get_predicates_for_cazy",
]
