"""
PFAM domain to predicate mappings.

``data/pfam_predicates.tsv`` is generated by ``scripts/build_pfam_predicate_map.py``:
every (family, predicate) pair in it is supported by the family's InterPro GO
annotation, its Pfam name/description, or an ENZYME name in its description,
and records that evidence. Proposals (curated rows and name/description
patterns) live in ``data/pfam_predicate_proposals.tsv`` and
``data/pfam_predicate_proposal_patterns.tsv``; edit those and rebuild.

Lookup is static: a hit maps through its accession, or through its profile name
when Stage 07 stored the name in the accession column.
"""

from pathlib import Path

from sharur.predicates.pfam_identity import normalize_pfam_accession


PFAM_MAPPING_FILE = Path(__file__).with_name("data") / "pfam_predicates.tsv"


def _load_pfam_mapping_file(path: Path) -> tuple[dict[str, list[str]], dict[str, dict[str, str]]]:
    """Load the generated map; returns predicates and evidence keyed by accession and name."""
    predicates: dict[str, list[str]] = {}
    evidence: dict[str, dict[str, str]] = {}
    with path.open() as handle:
        for line_number, raw_line in enumerate(handle, start=1):
            if not raw_line.strip() or raw_line.startswith("#"):
                continue
            parts = raw_line.rstrip("\n").split("\t")
            if len(parts) != 4:
                raise ValueError(f"{path}:{line_number}: expected accession, name, predicates, evidence")
            accession, name, preds, ev = parts
            pred_list = sorted(p for p in preds.split(",") if p)
            ev_map = dict(item.split("=", 1) for item in ev.split(";") if item)
            if set(ev_map) != set(pred_list):
                raise ValueError(f"{path}:{line_number}: evidence does not cover every predicate")
            if accession in predicates:
                raise ValueError(f"{path}:{line_number}: duplicate accession {accession!r}")
            predicates[accession] = pred_list
            evidence[accession] = ev_map
            # The build lists installed-release families first, so a profile name
            # reused by a later release stays with the family Astra reports.
            if name not in predicates:
                predicates[name] = pred_list
                evidence[name] = ev_map
    return predicates, evidence


PFAM_TO_PREDICATES, PFAM_EVIDENCE = _load_pfam_mapping_file(PFAM_MAPPING_FILE)


def get_predicates_for_pfam(accession: str, name: str = "", description: str = "") -> list[str]:
    """
    Get predicates for a PFAM domain.

    Args:
        accession: PFAM accession (e.g., "PF00005"), or the profile name when
            that is what the annotation stored
        name: PFAM short name (e.g., "ABC_tran")
        description: unused; kept for call compatibility

    Returns:
        List of predicate IDs
    """
    return list(PFAM_TO_PREDICATES.get(normalize_pfam_accession(accession), ()))


__all__ = [
    "PFAM_EVIDENCE",
    "PFAM_TO_PREDICATES",
    "get_predicates_for_pfam",
]
