#!/usr/bin/env python3
"""Precompute reviewed-protein consensus for KOs (maintainer step).

For each KO, reviewed UniProtKB/Swiss-Prot proteins linked to it through KEGG's
gene -> KO links (``scripts/link_swissprot_kegg.py``) vote with the predicates
of their curated EC numbers and experimental GO terms
(:func:`sharur.predicates.mappings.swissprot_evidence.ko_consensus`). Writes
``kegg_swissprot_consensus.tsv`` (KO, predicate, agreeing proteins, proteins):
IDs and counts only, shipped with Sharur and merged by ``sharur setup-kegg``.

Usage:
    python scripts/build_kegg_swissprot_consensus.py --swissprot uniprot_sprot.dat.gz \\
        --swissprot-release 2026_03 --swissprot-kegg swissprot_kegg_ko.tsv --go-obo go-basic.obo
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys
from collections import defaultdict
from pathlib import Path


sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sharur.predicates.mappings.swissprot_evidence import (
    go_ancestors,
    ko_consensus,
    protein_kos,
    read_gene_ko_links,
    read_swissprot,
)


DATA = Path(__file__).resolve().parents[1] / "sharur/predicates/mappings/data"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--swissprot", type=Path, required=True)
    parser.add_argument("--swissprot-release", required=True)
    parser.add_argument("--swissprot-kegg", type=Path, required=True)
    parser.add_argument("--go-obo", type=Path, required=True)
    args = parser.parse_args()

    proteins = read_swissprot(args.swissprot, go_ancestors(args.go_obo))
    gene_ko = read_gene_ko_links(args.swissprot_kegg)
    candidates: dict[str, set[str]] = defaultdict(set)
    for protein in proteins:
        for ko in protein_kos(protein, gene_ko):
            candidates[ko] |= protein.predicates
    consensus = ko_consensus(proteins, gene_ko, candidates)

    with open(DATA / "kegg_swissprot_consensus.tsv", "w") as out:
        out.write("# Reviewed-protein consensus per KO; generated by scripts/build_kegg_swissprot_consensus.py.\n"
                  f"# Swiss-Prot {args.swissprot_release} ({args.swissprot.name} sha256 {sha256(args.swissprot)[:16]}); "
                  f"KEGG gene links sha256 {sha256(args.swissprot_kegg)[:16]}; "
                  f"{args.go_obo.name} sha256 {sha256(args.go_obo)[:16]}\n"
                  "# ko\tpredicate\tagreeing\tproteins\n")
        for (ko, pred), ev in sorted(consensus.items()):
            k, n = ev.removeprefix("swissprot:").split("/")
            out.write(f"{ko}\t{pred}\t{k}\t{n}\n")
    print(f"{len(consensus):,} (KO, predicate) pairs over {len({ko for ko, _ in consensus}):,} KOs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
