#!/usr/bin/env python3
"""Score HydDB's labelled reference hydrogenases with KOfam profiles.

For every KO whose KEGG definition names a hydrogenase (EC 1.12, or
"hydrogenase"/"hydrogenlyase" in its name), runs ``hmmsearch`` of the KOfam
profile against the HydDB reference sequences and counts the HydDB labels of
references scoring at or above the KOfam threshold (full-sequence or best-domain
score, per ``ko_list``). ``scripts/build_kegg_predicate_map.py`` turns these
counts into ``hyddb:`` evidence. Output: ``kegg_hyddb_snapshot.tsv``.

Usage:
    python scripts/build_kegg_hyddb_snapshot.py --ko-list ko_list.tsv \\
        --kofam-dir ~/.config/Astra/KOFAM --kofam-ko-list data/reference/ko_list \\
        --hyddb-faa data/reference/hyddb/HydDB_all_hydrogenases.faa
"""

from __future__ import annotations

import argparse
import hashlib
import os
import subprocess
import sys
import tempfile
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path


sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sharur.hydrogenase.classifier import parse_reference_id
from sharur.predicates.mappings.kegg_evidence import names_hydrogenase


DATA = Path(__file__).resolve().parents[1] / "sharur/predicates/mappings/data"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_thresholds(path: Path) -> dict[str, tuple[float, str, str]]:
    with open(path) as handle:
        header = handle.readline().rstrip("\n").split("\t")
        rows = (dict(zip(header, line.rstrip("\n").split("\t"), strict=True)) for line in handle)
        return {r["knum"]: (float(r["threshold"]), r["score_type"], r["definition"])
                for r in rows if r["threshold"] != "-"}


def read_kegg_names(path: Path) -> dict[str, str]:
    names = {}
    with open(path) as handle:
        for line in handle:
            ko, _, definition = line.rstrip("\n").partition("\t")
            names[ko.removeprefix("ko:")] = definition
    return names


def ungapped_copy(faa: Path, out: Path) -> None:
    with open(faa) as src, open(out, "w") as dst:
        for line in src:
            dst.write(line if line.startswith(">") else line.replace("-", "").replace(".", "").replace("*", ""))


def score(ko: str, profile: Path, faa: Path, threshold: float, score_type: str) -> Counter:
    with tempfile.NamedTemporaryFile(suffix=".tbl") as tbl:
        subprocess.run(["hmmsearch", "--cpu", "1", "--noali", "-o", os.devnull, "--tblout", tbl.name,
                        str(profile), str(faa)], check=True)
        labels: Counter = Counter()
        for line in Path(tbl.name).read_text().splitlines():
            if line.startswith("#"):
                continue
            fields = line.split()
            value = float(fields[5] if score_type == "full" else fields[8])
            if value >= threshold:
                labels[parse_reference_id(fields[0])[2]] += 1
    return labels


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--ko-list", type=Path, required=True, help="KEGG REST list/ko snapshot")
    parser.add_argument("--kofam-dir", type=Path, required=True, help="Directory of KOfam <KO>.hmm profiles")
    parser.add_argument("--kofam-ko-list", type=Path, default=Path("data/reference/ko_list"))
    parser.add_argument("--hyddb-faa", type=Path, default=Path("data/reference/hyddb/HydDB_all_hydrogenases.faa"))
    parser.add_argument("--threads", type=int, default=os.cpu_count())
    args = parser.parse_args()

    thresholds = read_thresholds(args.kofam_ko_list)
    names = {**{ko: d for ko, (_, _, d) in thresholds.items()}, **read_kegg_names(args.ko_list)}
    eligible = sorted(ko for ko, name in names.items() if ko in thresholds and names_hydrogenase(name))

    with tempfile.TemporaryDirectory() as tmp:
        faa = Path(tmp) / "hyddb.faa"
        ungapped_copy(args.hyddb_faa, faa)
        with ThreadPoolExecutor(args.threads) as pool:
            counts = dict(zip(eligible, list(pool.map(
                lambda ko: score(ko, args.kofam_dir / f"{ko}.hmm", faa, *thresholds[ko][:2]), eligible)), strict=True))

    with open(DATA / "kegg_hyddb_snapshot.tsv", "w") as out:
        out.write("# HydDB reference labels per KO at the KOfam threshold; generated by "
                  "scripts/build_kegg_hyddb_snapshot.py.\n"
                  f"# HydDB: {args.hyddb_faa.name} sha256 {sha256(args.hyddb_faa)[:16]}; "
                  f"KOfam: {args.kofam_ko_list.name} sha256 {sha256(args.kofam_ko_list)[:16]}; "
                  f"{len(eligible)} KOs named as hydrogenases\n"
                  "# ko\treferences\tlabels\n")
        for ko in eligible:
            labels = counts[ko]
            out.write(f"{ko}\t{sum(labels.values())}\t"
                      f"{'|'.join(f'{label}={n}' for label, n in sorted(labels.items()))}\n")
    hit = sum(1 for c in counts.values() if c)
    print(f"{len(eligible)} hydrogenase-named KOs scored; {hit} capture HydDB references")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
