#!/usr/bin/env python3
"""Build the shipped CAZy family -> predicate map from evidence.

A (family, predicate) pair ships when

- ``class:<GH|GT|PL|CE|CBM|AA>``: CAZy's definition of the family's class states
  it (:data:`sharur.predicates.mappings.cazy_map.CAZY_CLASS_PREDICATES`); or
- ``swissprot:...``: reviewed UniProtKB/Swiss-Prot proteins cross-referenced to
  the family (``DR CAZy``) agree on it through curated EC numbers and
  experimental GO (coverage and attribution as for Pfam families; attribution
  counts the protein's catalytic CAZy families). Carbohydrate-binding modules
  are non-catalytic by CAZy's definition and take class predicates only.

Proposals (``cazy_predicate_proposals.tsv``) are judged against that evidence;
consensus may add predicates nobody proposed. Output: ``cazy_predicates.tsv``.

Usage:
    python scripts/build_cazy_predicate_map.py --swissprot uniprot_sprot.dat.gz \\
        --swissprot-release 2026_03 --go-obo go-basic.obo --report dropped_cazy_pairs.tsv
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys
from collections import defaultdict
from pathlib import Path


sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sharur.predicates.mappings.cazy_map import CAZY_CLASS_PREDICATES, cazy_class, cazy_family
from sharur.predicates.mappings.pfam_evidence import resolve
from sharur.predicates.mappings.swissprot_evidence import family_consensus, go_ancestors, read_swissprot
from sharur.predicates.vocabulary import PREDICATE_BY_ID


DATA = Path(__file__).resolve().parents[1] / "sharur/predicates/mappings/data"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_proposals() -> dict[str, set[str]]:
    proposals: dict[str, set[str]] = defaultdict(set)
    for line in (DATA / "cazy_predicate_proposals.tsv").read_text().splitlines():
        if line.strip() and not line.startswith("#"):
            family, preds = line.split("\t")[:2]
            proposals[family].update(p for p in preds.split(",") if p)
    return proposals


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--swissprot", type=Path, required=True)
    parser.add_argument("--swissprot-release", required=True)
    parser.add_argument("--go-obo", type=Path, required=True)
    parser.add_argument("--report", type=Path, help="TSV of proposed pairs that lack evidence")
    args = parser.parse_args()

    reviewed = [p for p in read_swissprot(args.swissprot, go_ancestors(args.go_obo)) if p.cazy]
    proteins = []  # (catalytic CAZy families, predicates, KOs) per reviewed protein
    for p in reviewed:
        catalytic = frozenset(cazy_family(f) for f in p.cazy if cazy_class(f) not in (None, "CBM"))
        if catalytic:
            proteins.append((catalytic, p.predicates, frozenset()))
    families = {cazy_family(f) for p in reviewed for f in p.cazy} | set(read_proposals())

    shipped: dict[str, dict[str, str]] = {}
    for family in sorted(families):
        klass = cazy_class(family)
        if klass is None:
            continue
        for pred in CAZY_CLASS_PREDICATES[klass]:
            shipped.setdefault(family, {})[pred] = f"class:{klass}"

    candidates: dict[str, set[str]] = defaultdict(set)
    proposals = read_proposals()
    for family, preds in proposals.items():
        candidates[family] |= {r for r in (resolve(p, PREDICATE_BY_ID) for p in preds) if r}
    for fams, preds, _ in proteins:
        for family in fams:
            candidates[family] |= preds
    supported = {family: set(ev) for family, ev in shipped.items()}
    consensus = family_consensus(proteins, candidates, supported)
    added = 0
    for (family, pred), ev in sorted(consensus.items()):
        if pred not in shipped.get(family, {}):
            shipped.setdefault(family, {})[pred] = ev
            added += 1

    dropped = []
    for family, preds in sorted(proposals.items()):
        for proposed in sorted(preds):
            pred = resolve(proposed, PREDICATE_BY_ID)
            if pred not in shipped.get(family, {}):
                dropped.append((family, proposed, pred or "(no vocabulary equivalent)"))

    with open(DATA / "cazy_predicates.tsv", "w") as out:
        out.write("# Generated by scripts/build_cazy_predicate_map.py; edit the proposals, not this file.\n"
                  f"# Swiss-Prot {args.swissprot_release} ({args.swissprot.name} sha256 {sha256(args.swissprot)[:16]}; "
                  f"{len(reviewed):,} reviewed proteins with CAZy); {args.go_obo.name} sha256 {sha256(args.go_obo)[:16]}\n"
                  "# family\tpredicates\tevidence\n")
        for family, evidence in sorted(shipped.items()):
            out.write(f"{family}\t{','.join(sorted(evidence))}\t"
                      f"{';'.join(f'{p}={e}' for p, e in sorted(evidence.items()))}\n")
    if args.report:
        with open(args.report, "w") as rep:
            rep.write("family\tproposed\tresolved\n")
            for row in dropped:
                rep.write("\t".join(row) + "\n")
    print(f"{len(shipped):,} families, {sum(map(len, shipped.values())):,} pairs; "
          f"Swiss-Prot consensus added {added:,}; proposed pairs without evidence: {len(dropped):,}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
