#!/usr/bin/env python3
"""List the EC numbers whose ENZYME reaction consumes S-adenosyl-L-methionine.

Reads Expasy ENZYME ``enzyme.dat`` (CC BY 4.0) and writes
``sharur/predicates/mappings/data/ec_sam_dependent.tsv``: every active EC whose
catalytic-activity (``CA``) lines name S-adenosyl-L-methionine as a reactant.
:func:`sharur.predicates.mappings.kegg_map.get_predicates_for_ec` adds
``sam_binding`` for these exact ECs.

Usage:
    python scripts/build_ec_sam_table.py --enzyme-dat enzyme.dat
"""

from __future__ import annotations

import argparse
import hashlib
from collections import defaultdict
from pathlib import Path


DATA = Path(__file__).resolve().parents[1] / "sharur/predicates/mappings/data"
SAM = "S-adenosyl-L-methionine"


def reactant_side(reaction: str) -> str:
    """Left-hand side of an ENZYME reaction (``A + B = C + D``)."""
    return reaction.split(" = ", 1)[0]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--enzyme-dat", type=Path, required=True)
    args = parser.parse_args()

    reactions: dict[str, str] = defaultdict(str)
    names: dict[str, str] = {}
    ec = None
    for line in open(args.enzyme_dat, encoding="latin-1"):
        tag, value = line[:2], line[5:].rstrip("\n").strip()
        if tag == "ID":
            ec = value
        elif tag == "DE" and ec:
            names[ec] = (names.get(ec, "") + " " + value).strip()
        elif tag == "CA" and ec:
            reactions[ec] += " " + value
    sam = sorted((e for e, r in reactions.items()
                  if SAM in reactant_side(r) and not names.get(e, "").startswith(("Transferred", "Deleted"))),
                 key=lambda e: [int(x) if x.isdigit() else 0 for x in e.split(".")])
    digest = hashlib.sha256(args.enzyme_dat.read_bytes()).hexdigest()[:16]
    with open(DATA / "ec_sam_dependent.tsv", "w") as out:
        out.write("# EC numbers whose ENZYME reaction consumes S-adenosyl-L-methionine; generated by "
                  f"scripts/build_ec_sam_table.py from {args.enzyme_dat.name} sha256 {digest} (Expasy ENZYME, CC BY 4.0)\n"
                  "# ec\tname\n")
        for e in sam:
            out.write(f"{e}\t{names.get(e, '').rstrip('.')}\n")
    print(f"{len(sam)} SAM-dependent ECs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
